name: lime
description: LIME Protocol for Dart/Flutter - A lightweight messaging library
version: 0.0.21
homepage: https://limeprotocol.org/
repository: https://github.com/takenet/lime-dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.5
  simple_logger: ^1.9.0
  pretty_json: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/keys/

false_secrets:
  - /assets/keys/certificate.cer
  - /assets/keys/private.key
